apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vc-chat-argo-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/ScaleupInfra/pull-gitops.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: pull-gitops
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
  