apiVersion: v1
kind: Service
metadata:
  name: pull-svc
spec:
  selector:
    name: pull-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-deploy
  labels:
    name: pull-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pull-pod
  template:
    metadata:
      labels:
        name: pull-pod
    spec:
      containers:
        - name: pull-container
          image: garvit3835/pull-gitops:4ce68e07a2d0a7d41f9c8611741cbf58739e534d
          ports:
            - containerPort: 3000
