name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'k8s'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/pull-gitops:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update deployment.yaml
        run: |
          sed -E -i "s/garvit3835\/chat-ser[a-zA-Z0-9:/\-]+/garvit3835\/pull-gitops:${{ github.sha }}/g" k8s/deploy.yaml

      - name: Stage changes
        run: git add k8s/deploy.yaml

      - name: Set Git user identity
        run: |
          git config --global user.email "garvit3835@gmail.com"
          git config --global user.name "garvit3835"
    
      - name: Commit changes
        run: git commit -m "Update k8s manifest" k8s/deploy.yaml
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main